#ifndef ERRORS_H
#define ERRORS_H

#define NO_ERROR 0
#define ERROR 1
#define TIMEOUT_ERROR 1
#define PI_SENT_WRONG_RESPONSE_ERROR 2
#define SERIAL_TIMEOUT_ERROR 3


#define HIGH_PEEP 4
#define LOW_PEEP 5
#define HIGH_INSPIRATORY_PRESSURE 6
#define LOW_INSPIRATORY_PRESSURE 7
#define FLOW_SENSOR_NOT_WORKING 8
#define PRESSURE_SENSOR_NOT_WORKING 9
#define OXYGEN_SENSOR_NOT_WORKING 10
#define OXYGEN_ABNORMAL 11

#endif